export const CITY_LIST: string[] = [
  "pune",
  "puebla",
  "putrajaya",
  "punta arenas",
  "puerto vallarta",
  "puerto princesa",
  "pueblo",
  "pula",
  "puyallup",
  "puri",
  "puno",
  "puerto montt",
  "pucallpa",
  "purwokerto",
  "purwakarta",
  "punta gorda",
  "pullman",
  "puerto la cruz",
  "punto fijo",
  "purnia",
  "purulia",
  "puttur",
  "punalur",
  "puerto asis",
  "puerto cabello",
  "putnam",
  "puertollano",
  "puerto del rosario",
  "puerto maldonado",
  "punakha",

  "paris",
  "prague",
  "pune",
  "phoenix",
  "philadelphia",
  "portland",
  "perth",
  "pretoria",
  "pyongyang",
  "phnom penh",
  "porto",
  "palermo",
  "pisa",
  "patna",
  "peshawar",
  "plano",
  "pasadena",
  "paterson",
  "peoria",
  "pomona",
  "palmdale",
  "providence",
  "pueblo",
  "provo",
  "potsdam",
  "plymouth",
  "portsmouth",
  "preston",
  "peterborough",
  "padua",
  "parma",
  "perugia",
  "plovdiv",
  "poznan",
  "panipat",
  "patiala",
  "pondicherry",
  "phuket",
  "pattaya",
  "petaling jaya",
  "palembang",
  "pekanbaru",
  "puebla",
  "porto alegre",
  "pereira",
  "potosi",
  "paramaribo",
  "punta arenas",
  "port harcourt",
  "pointe-noire",
  "panama city",
  "port moresby",
  "port louis",
  "port vila",
  "palikir",
  "podgorica",
  "pristina",
  "papeete",
  "pago pago",
  "palu",
  "pontianak",
  "padang",
  "pemba",
  "piura",
  "pucallpa",
  "puerto montt",
  "puerto varas",
  "puerto vallarta",
  "playa del carmen",
  "pensacola",
  "pompano beach",
  "port st. lucie",
  "palm bay",
  "plantation",
  "pinellas park",
  "palakkad",
  "panaji",
  "porbandar",
  "palanpur",
  "pali",
  "panchkula",
  "purnia",
  "puri",
  "paradip",
  "phusro",
  "pilibhit",
  "probolinggo",
  "pasuruan",
  "purwokerto",
  "pekalongan",
  "pematangsiantar",
  "pagadian",
  "panabo",
  "pasig",
  "paranaque",
  "pasay",
  "polokwane",
  "pietermaritzburg",
  "paarl",
  "paphos",
];
